---
- name: "Bump the plugin {{ item.name }} archive"
  become: true
  unarchive:
    src: "files/grafana/plugins/{{ item.file }}"
    dest: "{{ grafana_data_dir }}/plugins"
    mode: "u=rwX,g=rX,o=rX"
    owner: "{{ grafana_system_user }}"
    group: "{{ grafana_group_user }}"
  check_mode: false
  notify:
    - restart grafana
